name: Generate config JSON schema

on:
  push:
    branches:
      - main
    paths:
      - 'backend/config/*.go'
      - '!backend/config/config_default.go'
      - '!backend/config/**test.go'

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          path: hanko

      - name: Generate config JSON schema
        working-directory: ./hanko/backend
        run: |
          go generate ./...
          go run main.go schema generate config

      - name: Commit and and create branch
        working-directory: ./hanko
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git checkout -b "chore-autogenerate-config-json-schema"
            git commit -m "chore: autogenerate config JSON schema"
            git push origin HEAD
          else
            echo "No changes detected, skipping commit and pull request creation."
          fi

      - name: Create pull request
        working-directory: ./hanko
        run: >
          gh pr create
            -B main
            -r lfleischmann
            -H "chore-autogenerate-config-json-schema"
            -t "chore: Autogenerate config JSON schema"
            -b 'Created by Github Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
