name: Generate config JSON schema

on:
  push:
    branches:
      - main
    paths:
      - 'backend/config/*.go'
      - '!backend/config/config_default.go'
      - '!backend/config/**test.go'

jobs:
  config:
    runs-on: ubuntu-latest
    steps:
      - name: Delay check
        run: |
          OWNER=${{ github.repository_owner }}
          NAME="$(cut -f2 -d'/' <<< ${{ github.repository }})"
          HEAD_SHA="${{ github.sha }}"
          STATUS="in_progress"
          BASE="/repos/${OWNER}/${NAME}/actions/workflows/schema-generate-import.yml/runs"
          REQUEST_URL="${BASE}?head_sha=${HEAD_SHA}&status=${STATUS}"
          DELAY=$(gh api "$REQUEST_URL" --jq 'any(.workflow_runs | length; length > 0)')
          if [ "$DELAY" = "true" ]; then
            echo "Import schema generation job in progress, delaying to avoid conflicts";
            sleep 30s
          fi
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Checkout backend
        uses: actions/checkout@v4
        with:
          path: hanko

      - name: Generate config JSON schema
        working-directory: ./hanko/backend
        run: |
          go generate ./...
          go run main.go schema generate config

      - name: Commit and push to repo
        working-directory: ./hanko
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: autogenerate config JSON schema"
            git pull origin main --rebase
            git push origin HEAD
          else
            echo "No changes detected, skipping commit and push."
          fi
